[colors]
# background = "#1d1f21"

[env]
TERM = "alacritty"

[font]
size = 10.0

[font.bold]
family = "Iosevka NF"
style = "Bold"

[font.bold_italic]
family = "Iosevka NF"
style = "Bold Italic"

[font.italic]
family = "Iosevka NF"
style = "Italic"

[font.normal]
family = "Iosevka NF"
style = "Regular"

[window]
decorations = "None"
dynamic_padding = true

[colors.normal]
black = "#000000"
red = "#666666"
green = "#666666"
yellow = "#999999"
blue = "#CCCCCC"
magenta = "#DDDDDD"
cyan = "#EEEEEE"
white = "#FFFFFF"

[colors.bright]
black = "#595959"
red = "#666666"
green = "#999999"
yellow = "#CCCCCC"
blue = "#DDDDDD"
magenta = "#EEEEEE"
cyan = "#FFFFFF"
white = "#FFFFFF"
